_target_: scalingup.policy.llm_task_generator.FactorizedLLMTaskGenerator
temperature: 0.0
seed: 0
remove_with_statement: False
prompt:
  _target_: scalingup.utils.openai_api.Prompt
  config:
    _target_: scalingup.utils.openai_api.PromptConfig
    base_prompt: ${eval:'"".join(open("scalingup/prompts/task_generator/high_level_api_v6.py", "r").readlines())'}
    query_prefix: ''
    query_suffix: ''
    maintain_session: False
api_config:
  _target_: scalingup.utils.openai_api.GPT3APIConfig
  _convert_: 'all'
  engine: gpt-3.5-turbo-instruct
  temperature: 0.0
  max_tokens: 1024
  frequency_penalty: 0.0
  stop: ['# robot task', 'def']
state_encoder:
  _target_: scalingup.policy.llm_policy_utils.LanguageStateEncoder
  line_prefix: '# '
  obj_bullet: '-'
  link_bullet: '+'
